name: cli_progress_bar
description: Package for creating cli progress bar, customizing it.
version: 1.0.3
repository: https://github.com/GlebBatykov/cli_progress_bar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console: ^1.2.0

topics:
  - cli
  - progress
  - bar

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
